version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pipenv-{{ checksum "Pipfile.lock" }}
            - v1-pipenv-
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          paths:
            - .venv
          key: v1-pipenv-{{ checksum "Pipfile.lock" }}
      - run:
          name: run tests
          command: pipenv run pytest --cov
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
